name: Generate My Badges

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday
  workflow_dispatch: # Allows manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Badges
        run: npx update-my-badges ${{ github.repository_owner }} --omit="stars,followers,experience"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit Badge Images
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badges"
          branch: master
          file_pattern: "my-badges/**"
