name: Generate My Badges
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Badges
        uses: antonmedv/my-badges@master
        with:
          user_id: GARMA-A
          omit: "stars, followers, experience"
      - name: Commit Badge Images
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badges"
          branch: master
          file_pattern: "my-badges/**"
